# Generated by Django 5.2 on 2025-04-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_alter_mentorados_estagio_disponibilidadehorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorados',
            name='estagio',
            field=models.CharField(choices=[('E1', '3k-10k'), ('E2', '10k-100k'), ('E3', '100k-1kk'), ('E4', '1kk-10kk'), ('E5', '10kk+')], max_length=2),
        ),
    ]
