# Generated by Django 5.2 on 2025-04-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_mentorados_token_alter_mentorados_estagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('G', 'Gestão'), ('M', 'Marketing'), ('RH', 'Gestão de pessoas'), ('I', 'Impostos'), ('E', 'Empreendedorismo'), ('F', 'Finanças'), ('T', 'Tecnologia'), ('P', 'Produto'), ('V', 'Vendas'), ('CS', 'Customer Success'), ('D', 'Desenvolvimento Pessoal'), ('N', 'Networking'), ('S', 'Startup'), ('L', 'Liderança'), ('DA', 'Análise de Dados'), ('J', 'Jurídico'), ('O', 'Operações'), ('X', 'Outros')], max_length=2)),
                ('descricao', models.TextField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.disponibilidadehorarios')),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados')),
            ],
        ),
    ]
